### ISSUE TITLE
How is network key supposed to be set?

### ISSUE THREAD

**Issue by David-Hari** [SamyCookie/python-ant#5]
The original code from @mvillalba had a `NetworkKey` object that held the number and key, and was passed to `setNetworkKey`.
Your code does away with the object, but `setNetworkKey` still tries to access properties of the `network` variable.
If I call `setNetworkKey` with an integer and a bytearray, I get the error:

```
'str' object has no attribute 'key'
```

Is this a mistake in your code (which you've somehow missed all this time), or am I doing something wrong?

**Comment by David-Hari** [comment]
Similar problems with assigning a channel.

**Comment by SamyCookie** [comment]
I think it's a regression.
https://github.com/SamyCookie/python-ant/commit/efe8694874c3c3029c5e8a4aca58f6a3a522ad5e#diff-3f8cf9f5f1e5d5381a14d76efe2b0617  is the bad commit.

**Comment by SamyCookie** [comment]
Or not. I have not access to my frontend code, but in fact the 'key' parameter seems to have a really bad name.
'setNetworkKey' seems to get a 'Network' object for its second parameter, not directly a key.
try for example:

```
network = Network(key, name)
node.setNetworkey(number, network)
```

**Comment by David-Hari** [comment]
Huh, I didn't see the `Network` object. I thought you had removed the entire class. I don't know why I missed it, it's right at the top of the file!

**Comment by SamyCookie** [comment]
I made a small cleaning commit to rename 'key' variable to 'network'. It is now less confusing.
22e85dc6f145c52b4c8e9bada3591b40e87ea194
